version: '3.7'
services:
  account-service:
    build:
      context: ./account
    environment:
      - MONGO_URI=mongodb+srv://ruslan:ruslan1@cluster0-hnkkh.mongodb.net/test?retryWrites=true&w=majority
    ports:
      - "8000:3000"
    depends_on:
      - mongodb
    networks:
      - microservices
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
networks:
  microservices: